export const GAME_TITLE = 'VAULT RECOVERY';
export const SAVE_KEY = 'vault-recovery-save-v1';
export const SAVE_VERSION = 1;

export const RARITIES = {
  common: {
    id: 'common',
    label: '일반',
    weight: 66,
    valueMultiplier: 1,
    reputationBonus: 0,
  },
  uncommon: {
    id: 'uncommon',
    label: '고급',
    weight: 23,
    valueMultiplier: 1.35,
    reputationBonus: 1,
  },
  rare: {
    id: 'rare',
    label: '희귀',
    weight: 8,
    valueMultiplier: 1.9,
    reputationBonus: 2,
  },
  legendary: {
    id: 'legendary',
    label: '전설',
    weight: 3,
    valueMultiplier: 3.25,
    reputationBonus: 4,
  },
};

export const JOBS = [
  {
    id: 'harbor-branch',
    order: 1,
    name: '항구 3동 폐점은행',
    shortName: '폐점은행',
    client: '청산관리공사',
    briefing: '30년 동안 잠겨 있던 기계식 개인 금고입니다. 잠금핀이 낡아 압력을 세게 주면 내부 물품이 손상됩니다.',
    difficulty: 1,
    unlockReputation: 0,
    entryFee: 0,
    baseReward: 90,
    timeLimit: 42,
    accent: 'cyan',
    environment: 'dust',
    lootTags: ['personal', 'documents', 'coins'],
  },
  {
    id: 'baekya-hotel',
    order: 2,
    name: '백야호텔 지하 금고',
    shortName: '호텔 금고',
    client: '호텔 재건위원회',
    briefing: '화재로 전자제어부가 녹았습니다. 내부 온도를 관리하면서 수동 잠금축 네 개를 순서대로 풀어야 합니다.',
    difficulty: 2,
    unlockReputation: 4,
    entryFee: 55,
    baseReward: 170,
    timeLimit: 40,
    accent: 'amber',
    environment: 'embers',
    lootTags: ['jewelry', 'personal', 'collectible'],
  },
  {
    id: 'submerged-central',
    order: 3,
    name: '침수된 중앙지점',
    shortName: '침수 지점',
    client: '도시재난본부',
    briefing: '수압과 부식 때문에 잠금장치가 불규칙하게 움직입니다. 소음이 누적되면 비상 셔터가 다시 내려옵니다.',
    difficulty: 3,
    unlockReputation: 10,
    entryFee: 115,
    baseReward: 290,
    timeLimit: 38,
    accent: 'blue',
    environment: 'water',
    lootTags: ['documents', 'evidence', 'coins', 'collectible'],
  },
  {
    id: 'national-bunker',
    order: 4,
    name: '폐쇄 국고 벙커 B-7',
    shortName: '국고 벙커',
    client: '기록보존국',
    briefing: '구형 군용 잠금장치와 진동 감지기가 함께 작동합니다. 완벽한 압력 제어 없이는 끝까지 도달하기 어렵습니다.',
    difficulty: 4,
    unlockReputation: 20,
    entryFee: 240,
    baseReward: 520,
    timeLimit: 36,
    accent: 'red',
    environment: 'bunker',
    lootTags: ['evidence', 'documents', 'collectible', 'jewelry'],
  },
];

export const ITEMS = [
  {
    id: 'silver-watch',
    name: '멈춘 은제 회중시계',
    icon: '◷',
    rarity: 'common',
    baseValue: 95,
    tags: ['personal', 'collectible'],
    story: '뒷면에 서로 다른 두 사람의 이니셜이 얕게 새겨져 있다.',
  },
  {
    id: 'foreign-coins',
    name: '낡은 해외 주화 묶음',
    icon: '◉',
    rarity: 'common',
    baseValue: 80,
    tags: ['coins', 'collectible'],
    story: '여러 나라의 주화가 여행 날짜별로 작은 봉투에 나뉘어 있다.',
  },
  {
    id: 'family-photo',
    name: '빛바랜 가족사진',
    icon: '▣',
    rarity: 'common',
    baseValue: 45,
    tags: ['personal'],
    story: '사진 속 사람들은 은행 앞 계단에서 같은 방향을 바라보고 있다.',
  },
  {
    id: 'sealed-ledger',
    name: '봉인된 거래 장부',
    icon: '▤',
    rarity: 'common',
    baseValue: 110,
    tags: ['documents', 'evidence'],
    story: '마지막 열두 장만 다른 잉크로 급하게 작성되어 있다.',
  },
  {
    id: 'porcelain-token',
    name: '백자 보관표',
    icon: '⬡',
    rarity: 'uncommon',
    baseValue: 165,
    tags: ['collectible', 'personal'],
    story: '금속 대신 백자로 만든 오래된 보관표. 같은 문양의 짝이 어딘가에 남아 있다.',
  },
  {
    id: 'ruby-ring',
    name: '붉은 유리 반지',
    icon: '◇',
    rarity: 'uncommon',
    baseValue: 210,
    tags: ['jewelry', 'personal'],
    story: '보석은 유리지만 세공은 당대 최고 수준이다. 안쪽에 짧은 약속 문구가 있다.',
  },
  {
    id: 'architect-tube',
    name: '구도심 지하도 설계도',
    icon: '⌁',
    rarity: 'uncommon',
    baseValue: 240,
    tags: ['documents', 'evidence'],
    story: '현재 지도에는 없는 통로가 은행 지하에서 강변까지 이어진다.',
  },
  {
    id: 'cassette-confession',
    name: '무제 카세트테이프',
    icon: '▰',
    rarity: 'uncommon',
    baseValue: 190,
    tags: ['personal', 'evidence'],
    story: '라벨은 비어 있지만 첫 구간에 누군가의 떨리는 목소리가 녹음돼 있다.',
  },
  {
    id: 'meteor-fragment',
    name: '운석 조각 문진',
    icon: '✦',
    rarity: 'rare',
    baseValue: 420,
    tags: ['collectible'],
    story: '지역 천문대 폐쇄 당시 사라진 표본 번호가 바닥에 남아 있다.',
  },
  {
    id: 'emerald-brooch',
    name: '에메랄드 제비 브로치',
    icon: '◆',
    rarity: 'rare',
    baseValue: 510,
    tags: ['jewelry', 'personal'],
    story: '실종된 무대 배우의 마지막 공연 사진에서 같은 브로치가 보인다.',
  },
  {
    id: 'prototype-bond',
    name: '미발행 시험 채권',
    icon: '▥',
    rarity: 'rare',
    baseValue: 560,
    tags: ['documents', 'collectible'],
    story: '공식 기록에 없는 인쇄본. 일련번호가 모두 0으로 시작한다.',
  },
  {
    id: 'gold-molar',
    name: '금니가 든 작은 상자',
    icon: '⌂',
    rarity: 'rare',
    baseValue: 470,
    tags: ['personal', 'evidence'],
    story: '치과 차트 일부와 함께 보관돼 있다. 상자 주인은 자신이 의사가 아니라고 기록했다.',
  },
  {
    id: 'royal-seal',
    name: '분실된 황동 국새 모형',
    icon: '♜',
    rarity: 'legendary',
    baseValue: 980,
    tags: ['collectible', 'evidence'],
    story: '박물관 도난 목록에는 진품으로 기록되어 있지만 바닥에는 모형이라는 각인이 있다.',
  },
  {
    id: 'blue-diamond',
    name: '푸른 다이아 원석',
    icon: '⬙',
    rarity: 'legendary',
    baseValue: 1250,
    tags: ['jewelry'],
    story: '감정 기록이 전혀 없는 원석. 빛을 비추면 내부에 별 모양 균열이 나타난다.',
  },
  {
    id: 'black-book',
    name: '검은 명부 17번',
    icon: '▦',
    rarity: 'legendary',
    baseValue: 1120,
    tags: ['documents', 'evidence'],
    story: '페이지마다 같은 날짜와 다른 이름이 반복된다. 마지막 줄은 아직 비어 있다.',
  },
  {
    id: 'moon-key',
    name: '월식 문양의 두 번째 열쇠',
    icon: '⚿',
    rarity: 'legendary',
    baseValue: 1380,
    tags: ['collectible', 'personal'],
    story: '첫 번째 열쇠가 존재한다는 메모와 함께 보관되어 있다. 어느 자물쇠의 것인지는 알 수 없다.',
  },
];

export const UPGRADE_DEFINITIONS = {
  drill: {
    id: 'drill',
    name: '정밀 드릴',
    icon: '⌁',
    description: '압력 상승을 부드럽게 하고 금고 해체 속도를 높입니다.',
    baseCost: 180,
    growth: 1.68,
    maxLevel: 6,
  },
  coolant: {
    id: 'coolant',
    name: '냉각 순환기',
    icon: '❄',
    description: '작업 중 발생하는 열을 낮춰 물품 손상을 줄입니다.',
    baseCost: 150,
    growth: 1.62,
    maxLevel: 6,
  },
  muffler: {
    id: 'muffler',
    name: '방진 흡음재',
    icon: '≋',
    description: '소음과 진동을 억제해 보안 경보가 울리는 시점을 늦춥니다.',
    baseCost: 165,
    growth: 1.65,
    maxLevel: 6,
  },
  scanner: {
    id: 'scanner',
    name: '투과 스캐너',
    icon: '⌖',
    description: '가치 있는 물품이 든 보관함을 찾아낼 확률을 높입니다.',
    baseCost: 240,
    growth: 1.72,
    maxLevel: 6,
  },
};

export function getJobById(jobId) {
  return JOBS.find((job) => job.id === jobId) ?? null;
}

export function getItemById(itemId) {
  return ITEMS.find((item) => item.id === itemId) ?? null;
}
